import {
  FileText,
  Lock,
  LockOpen,
  Terminal,
  Mail,
  Globe,
  Wifi,
  Inbox,
  ShieldCheck,
  Database,
  Monitor,
  Plug,
  Split,
  Radar,
  Swords,
  Zap,
  LayoutGrid,
  Gauge,
  Rocket,
  Compass,
  Award,
  BookOpen,
  FileChartColumn,
  Crown,
  Shield,
  type LucideIcon,
} from 'lucide-react-native';

const MAP: Record<string, LucideIcon> = {
  'file-text': FileText,
  lock: Lock,
  'lock-open': LockOpen,
  terminal: Terminal,
  mail: Mail,
  globe: Globe,
  wifi: Wifi,
  inbox: Inbox,
  'shield-check': ShieldCheck,
  database: Database,
  monitor: Monitor,
  plug: Plug,
  split: Split,
  unlock: LockOpen,
  radar: Radar,
  swords: Swords,
  zap: Zap,
  'layout-grid': LayoutGrid,
  gauge: Gauge,
  rocket: Rocket,
  compass: Compass,
  award: Award,
  'book-open': BookOpen,
  'file-bar-chart': FileChartColumn,
  'file-chart-column': FileChartColumn,
  crown: Crown,
  shield: Shield,
};

export function getIcon(name: string): LucideIcon {
  return MAP[name] ?? Shield;
}
